version: '3.8'  # You can remove this line if you want to avoid the warning
services:
  postgres:
    image: postgres:15
    container_name: e_gov_postgres
    restart: always
    environment:
      POSTGRES_USER: egov_user
      POSTGRES_PASSWORD: egov_pass
      POSTGRES_DB: e_gov_portal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: e_gov_keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: e_gov_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   # change as needed
      PGADMIN_DEFAULT_PASSWORD: admin          # change as needed
    ports:
      - "5050:80"                              # access pgAdmin at http://localhost:5050
    depends_on:
      - postgres

volumes:
  pgdata: