server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html pages/login.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy auth calls to the NestJS backend
    location /auth/ {
        proxy_pass http://nestjs-api:3000/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy ID renewal API to backend
    location /id-renewal/ {
        proxy_pass http://nestjs-api:3000/id-renewal/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
